# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: menuan
  demands:
  - docker
  - elixir-mix

variables:
  AZURE_SUBSCRIPTION: 'menuan (c61ac7e7-acd8-4a30-a5c3-d3efedc06f90)'
  AZURE_RESOURCE_GROUP: ''
  KUBERNETES_CLUSTER: ''
  IMAGE_TAG: ''
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# - bash
  
- task: Docker@1
  displayName: 'Push image and its tags'
  inputs:
    azureSubscriptionEndpoint: '$(AZURE_SUBSCRIPTION)'
    azureContainerRegistry: menuan.azurecr.io
    command: 'Push an image'
    pushMultipleImages: true
    imageNamesPath: .docker/images.txt

- task: HelmDeploy@0
  displayName: 'Upgrade deployment'
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    azureResourceGroup: '$(AZURE_RESOURCE_GROUP)'
    kubernetesCluster: '$(KUBERNETES_CLUSTER)'
    namespace: 'slack'
    command: upgrade
    chartType: FilePath
    chartPath: '.helm'
    releaseName: 'kemisten'
    overrideValues: 'image.tag=$(IMAGE_TAG),slack.secret.name=kemisten-token,slack.secret.key=token'
