apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name | default "kemisten" }}
  namespace: { .Release.Namespace | default "default" }
  labels:
    app: {{ include "kemisten.name" . }}
    chart: {{ include "kemisten.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kemisten.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kemisten.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          resources:
{{ toYaml .Values.resources | indent 12 }}
